#!/usr/bin/env zsh
# shellcheck shell=bash

#
# ~/.zprofile: sourced in login shells, before .zshrc
#
#  - Should contain commands that should be executed only in login shells
#
# https://zsh.sourceforge.io/Intro/intro_3.html
#

profile="${XDG_CONFIG_HOME:-$HOME/.config}/dotfiles/configs/profile.sh"

# Load shell profile to share environment variables, etc.
# shellcheck disable=1090
if [ ! -r "$profile" ] || ! source "$profile"; then
  printf '[error] %s\n' "file not loaded: $profile"
  return 1
fi

log:debug "file loaded: $profile"
unset profile

# @todo move dotfiles into a zdotdir, maybe move this back to zshenv?
# export ZDOTDIR=$HOME/.dotfiles/zdotdir
