#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

unsetopt NOMATCH

# Import aliases
if [ -f ~/.zsh_aliases ]; then
  . ~/.zsh_aliases
fi

# Import notifyosd.zsh
[ -e $HOME/.config/notifyosd.zsh/notifyosd.zsh ] && . $HOME/.config/notifyosd.zsh/notifyosd.zsh

